version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mindset_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
