// ... existing code ...

const users = [
  {
    firstName: 'Thomas',
    lastName: 'Quan',
    fullName: 'Thomas Quan',
    email: process.env.ADMIN_EMAIL,
    password: process.env.ADMIN_PASSWORD,
    status: 'ACTIVE',
    title: 'Full-Stack Engineer: Mastering Digital Realms with Precision',
    headline:
      'A Wizard in Technology, Crafting Seamless Solutions and Rolling Nat 20s on Innovation',
    role: {
      connect: {
        slug: 'administrator',
      },
    },
  },
];

const roles = [
  {
    title: 'Administrator',
    slug: 'administrator',
    description: 'Full access to all system features',
  },
  {
    title: 'Regular User',
    slug: 'regular-user',
    description: 'Standard user with limited access',
  },
];

const permissions = [
  {
    title: 'Create Blog Permission',
    slug: 'create-blog-permission',
    description: 'Allow admin to create a blog',
    referenceModel: 'blog',
    action: 'create',
  },
  {
    title: 'Read Blog Permission',
    slug: 'read-blog-permission',
    description: 'Allow admin to read blogs',
    referenceModel: 'blog',
    action: 'read',
  },
  {
    title: 'Update Blog Permission',
    slug: 'update-blog-permission',
    description: 'Allow admin to update a blog',
    referenceModel: 'blog',
    action: 'update',
  },
  {
    title: 'Delete Blog Permission',
    slug: 'delete-blog-permission',
    description: 'Allow admin to delete a blog',
    referenceModel: 'blog',
    action: 'delete',
  },
  // Project permissions
  {
    title: 'Create Project Permission',
    slug: 'create-project-permission',
    description: 'Allow admin to create a project',
    referenceModel: 'project',
    action: 'create',
  },
  {
    title: 'Read Project Permission',
    slug: 'read-project-permission',
    description: 'Allow admin to read projects',
    referenceModel: 'project',
    action: 'read',
  },
  {
    title: 'Update Project Permission',
    slug: 'update-project-permission',
    description: 'Allow admin to update a project',
    referenceModel: 'project',
    action: 'update',
  },
  {
    title: 'Delete Project Permission',
    slug: 'delete-project-permission',
    description: 'Allow admin to delete a project',
    referenceModel: 'project',
    action: 'delete',
  },
  // Content permissions
  {
    title: 'Create Content Permission',
    slug: 'create-content-permission',
    description: 'Allow admin to create content',
    referenceModel: 'content',
    action: 'create',
  },
  {
    title: 'Read Content Permission',
    slug: 'read-content-permission',
    description: 'Allow admin to read content',
    referenceModel: 'content',
    action: 'read',
  },
  {
    title: 'Update Content Permission',
    slug: 'update-content-permission',
    description: 'Allow admin to update content',
    referenceModel: 'content',
    action: 'update',
  },
  {
    title: 'Delete Content Permission',
    slug: 'delete-content-permission',
    description: 'Allow admin to delete content',
    referenceModel: 'content',
    action: 'delete',
  },
  // Asset permissions
  {
    title: 'Create Asset Permission',
    slug: 'create-asset-permission',
    description: 'Allow admin to create an asset',
    referenceModel: 'asset',
    action: 'create',
  },
  {
    title: 'Read Asset Permission',
    slug: 'read-asset-permission',
    description: 'Allow admin to read assets',
    referenceModel: 'asset',
    action: 'read',
  },
  {
    title: 'Update Asset Permission',
    slug: 'update-asset-permission',
    description: 'Allow admin to update an asset',
    referenceModel: 'asset',
    action: 'update',
  },
  {
    title: 'Delete Asset Permission',
    slug: 'delete-asset-permission',
    description: 'Allow admin to delete an asset',
    referenceModel: 'asset',
    action: 'delete',
  },
  // Tag permissions
  {
    title: 'Create Tag Permission',
    slug: 'create-tag-permission',
    description: 'Allow admin to create a tag',
    referenceModel: 'tag',
    action: 'create',
  },
  {
    title: 'Read Tag Permission',
    slug: 'read-tag-permission',
    description: 'Allow admin to read tags',
    referenceModel: 'tag',
    action: 'read',
  },
  {
    title: 'Update Tag Permission',
    slug: 'update-tag-permission',
    description: 'Allow admin to update a tag',
    referenceModel: 'tag',
    action: 'update',
  },
  {
    title: 'Delete Tag Permission',
    slug: 'delete-tag-permission',
    description: 'Allow admin to delete a tag',
    referenceModel: 'tag',
    action: 'delete',
  },
  // User permissions
  {
    title: 'Create User Permission',
    slug: 'create-user-permission',
    description: 'Allow admin to create a user',
    referenceModel: 'user',
    action: 'create',
  },
  {
    title: 'Read User Permission',
    slug: 'read-user-permission',
    description: 'Allow admin to read users',
    referenceModel: 'user',
    action: 'read',
  },
  {
    title: 'Update User Permission',
    slug: 'update-user-permission',
    description: 'Allow admin to update a user',
    referenceModel: 'user',
    action: 'update',
  },
  {
    title: 'Delete User Permission',
    slug: 'delete-user-permission',
    description: 'Allow admin to delete a user',
    referenceModel: 'user',
    action: 'delete',
  },
  // Role permissions
  {
    title: 'Create Role Permission',
    slug: 'create-role-permission',
    description: 'Allow admin to create a role',
    referenceModel: 'role',
    action: 'create',
  },
  {
    title: 'Read Role Permission',
    slug: 'read-role-permission',
    description: 'Allow admin to read roles',
    referenceModel: 'role',
    action: 'read',
  },
  {
    title: 'Update Role Permission',
    slug: 'update-role-permission',
    description: 'Allow admin to update a role',
    referenceModel: 'role',
    action: 'update',
  },
  {
    title: 'Delete Role Permission',
    slug: 'delete-role-permission',
    description: 'Allow admin to delete a role',
    referenceModel: 'role',
    action: 'delete',
  },
  // Permission permissions
  {
    title: 'Create Permission Permission',
    slug: 'create-permission-permission',
    description: 'Allow admin to create a permission',
    referenceModel: 'permission',
    action: 'create',
  },
  {
    title: 'Read Permission Permission',
    slug: 'read-permission-permission',
    description: 'Allow admin to read permissions',
    referenceModel: 'permission',
    action: 'read',
  },
  {
    title: 'Update Permission Permission',
    slug: 'update-permission-permission',
    description: 'Allow admin to update a permission',
    referenceModel: 'permission',
    action: 'update',
  },
  {
    title: 'Delete Permission Permission',
    slug: 'delete-permission-permission',
    description: 'Allow admin to delete a permission',
    referenceModel: 'permission',
    action: 'delete',
  },
];

const tags = [
  // Frontend Technologies
  {
    title: 'React',
    slug: 'react',
    description: 'Popular JavaScript library for building user interfaces.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 1,
    color: '#61DAFB',
  },
  {
    title: 'Angular',
    slug: 'angular',
    description: 'Comprehensive JavaScript framework by Google.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 2,
    color: '#DD0031',
  },
  {
    title: 'Next.js',
    slug: 'next-js',
    description: 'React-based framework for server-side rendering.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 3,
    color: '#000000',
  },
  {
    title: 'TypeScript',
    slug: 'typescript',
    description: 'Superset of JavaScript with static types.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 4,
    color: '#3178C6',
  },
  {
    title: 'JavaScript',
    slug: 'javascript',
    description: 'The language of the web.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 5,
    color: '#F7DF1E',
  },
  {
    title: 'HTML',
    slug: 'html',
    description: 'Standard markup language for creating web pages.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 6,
    color: '#E34F26',
  },
  {
    title: 'CSS',
    slug: 'css',
    description: 'Style sheet language for designing web pages.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 7,
    color: '#1572B6',
  },
  {
    title: 'Tailwind',
    slug: 'tailwind',
    description: 'Utility-first CSS framework for rapid UI development.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 8,
    color: '#38B2AC',
  },
  {
    title: 'Sass',
    slug: 'sass',
    description: 'CSS extension language with nested rules and variables.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 9,
    color: '#CC6699',
  },
  {
    title: 'React Native',
    slug: 'react-native',
    description: 'Framework for building native apps using React.',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 10,
    color: '#61DAFB',
  },
  {
    title: 'NativeScript',
    slug: 'nativescript',
    description:
      'Open-source framework for building native mobile apps. (Dead now)',
    category: 'Frontend',
    categoryOrder: 1,
    tagOrder: 11,
    color: '#3655FF',
  },
  // Backend Technologies
  {
    title: 'Nest.js',
    slug: 'nest-js',
    description:
      'Progressive Node.js framework for building server-side applications.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 1,
    color: '#E0234E',
  },
  {
    title: 'Node.js',
    slug: 'node-js',
    description: 'JavaScript runtime for building server-side applications.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 2,
    color: '#339933',
  },
  {
    title: 'Express.js',
    slug: 'express-js',
    description: 'Fast, unopinionated Node.js web framework.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 3,
    color: '#000000',
  },
  {
    title: 'TypeORM',
    slug: 'typeorm',
    description: 'ORM for TypeScript and JavaScript (ES7, ES6, ES5).',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 4,
    color: '#FE0902',
  },
  {
    title: 'Prisma',
    slug: 'prisma',
    description: 'Next-generation ORM for Node.js and TypeScript.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 5,
    color: '#2D3748',
  },
  {
    title: 'GraphQL',
    slug: 'graphql',
    description: 'Query language for your API.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 6,
    color: '#E10098',
  },
  {
    title: 'Java',
    slug: 'java',
    description: 'Widely-used object-oriented programming language.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 7,
    color: '#007396',
  },
  {
    title: 'Spring',
    slug: 'spring',
    description: 'Java framework for building enterprise applications.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 8,
    color: '#6DB33F',
  },
  {
    title: 'Spring Boot',
    slug: 'spring-boot',
    description: 'Spring-based framework for rapid application development.',
    category: 'Backend',
    categoryOrder: 2,
    tagOrder: 9,
    color: '#6DB33F',
  },
  // Cloud Technologies
  {
    title: 'AWS S3',
    slug: 'aws-s3',
    description: 'Amazon S3 for scalable object storage.',
    category: 'Cloud',
    categoryOrder: 3,
    tagOrder: 1,
    color: '#569A31',
  },
  {
    title: 'AWS Lambda',
    slug: 'aws-lambda',
    description: 'Event-driven, serverless compute service.',
    category: 'Cloud',
    categoryOrder: 3,
    tagOrder: 2,
    color: '#FF9900',
  },
  {
    title: 'Digital Ocean',
    slug: 'digital-ocean',
    description: 'Cloud infrastructure provider for developers.',
    category: 'Cloud',
    categoryOrder: 3,
    tagOrder: 3,
    color: '#0080FF',
  },
  // Databases
  {
    title: 'PostgreSQL',
    slug: 'postgresql',
    description: 'Advanced open-source relational database.',
    category: 'Database',
    categoryOrder: 4,
    tagOrder: 1,
    color: '#336791',
  },
  {
    title: 'MySQL',
    slug: 'mysql',
    description: 'Popular open-source relational database.',
    category: 'Database',
    categoryOrder: 4,
    tagOrder: 2,
    color: '#4479A1',
  },
  {
    title: 'NoSQL',
    slug: 'nosql',
    description: 'Non-relational database paradigm.',
    category: 'Database',
    categoryOrder: 4,
    tagOrder: 3,
    color: '#4DB33D',
  },
  // DevOps
  {
    title: 'Docker',
    slug: 'docker',
    description:
      'Containerization platform for developing and deploying applications.',
    category: 'DevOps',
    categoryOrder: 5,
    tagOrder: 1,
    color: '#2496ED',
  },
  {
    title: 'CI/CD',
    slug: 'ci-cd',
    description: 'Continuous integration and continuous delivery practices.',
    category: 'DevOps',
    categoryOrder: 5,
    tagOrder: 2,
    color: '#41CD52',
  },
  // Monitoring & Testing
  {
    title: 'Sentry',
    slug: 'sentry',
    description: 'Error tracking that helps developers monitor and fix issues.',
    category: 'Monitoring',
    categoryOrder: 6,
    tagOrder: 1,
    color: '#362D59',
  },
  {
    title: 'DataDog',
    slug: 'datadog',
    description: 'Cloud monitoring as a service.',
    category: 'Monitoring',
    categoryOrder: 6,
    tagOrder: 2,
    color: '#632CA6',
  },
  {
    title: 'Cypress',
    slug: 'cypress',
    description: 'JavaScript-based end-to-end testing framework.',
    category: 'Testing',
    categoryOrder: 7,
    tagOrder: 1,
    color: '#17202C',
  },
  {
    title: 'Playwright',
    slug: 'playwright',
    description: 'Testing framework for modern web apps.',
    category: 'Testing',
    categoryOrder: 7,
    tagOrder: 2,
    color: '#2EAD33',
  },
  // Architecture
  {
    title: 'Domain Driven Design',
    slug: 'ddd',
    description: 'Approach to software development focused on complex domains.',
    category: 'Architecture',
    categoryOrder: 8,
    tagOrder: 1,
    color: '#FF7F50',
  },
  {
    title: 'Monolith',
    slug: 'monolith',
    description: 'Traditional single-tiered software architecture.',
    category: 'Architecture',
    categoryOrder: 8,
    tagOrder: 2,
    color: '#8B4513',
  },
  {
    title: 'Monorepo',
    slug: 'monorepo',
    description:
      'Software development strategy where code for many projects is stored in the same repository.',
    category: 'Architecture',
    categoryOrder: 8,
    tagOrder: 3,
    color: '#4B0082',
  },
  // Miscellaneous
  {
    title: 'Git',
    slug: 'git',
    description: 'Version control system for tracking changes in source code.',
    category: 'Misc',
    categoryOrder: 9,
    tagOrder: 1,
    color: '#F05032',
  },
  {
    title: 'SEO',
    slug: 'seo',
    description: 'Search engine optimization.',
    category: 'Misc',
    categoryOrder: 9,
    tagOrder: 2,
    color: '#47C2FF',
  },
];

export { users, roles, permissions, tags };
